### ISSUE TITLE
bot stops with error since yesterday

### ISSUE THREAD

**Issue by meadowocean** [miningseven/Stormgain_Bot#3]
Message: no such element: Unable to locate element: {"method":"css selector","selector":".md\3Atext-15 > span:nth-child(1)"}
  (Session info: chrome=89.0.4389.90)

**Comment by meadowocean** [comment]
1.
  switch to frame removed             
  # self.driver.switch_to.frame(0)
  
  2. locator changed
  html = self.driver.find_element_by_xpath(
                '//*[@id="region-main"]/div/div[2]/div/div[2]/div/div/div[1]/div[2]/span[1]').get_attribute('innerHTML')

**Comment by miningseven** [comment]
Perfect, was so adopted! thank you!
